/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUpgradeRouteImport } from './routes/app.upgrade'
import { Route as AppTodayRouteImport } from './routes/app.today'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppAppointmentsRouteImport } from './routes/app.appointments'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUpgradeRoute = AppUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AppRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/booking': typeof BookingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/clients': typeof AppClientsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/today': typeof AppTodayRoute
  '/app/upgrade': typeof AppUpgradeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/booking': typeof BookingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/clients': typeof AppClientsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/today': typeof AppTodayRoute
  '/app/upgrade': typeof AppUpgradeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/booking': typeof BookingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/clients': typeof AppClientsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/today': typeof AppTodayRoute
  '/app/upgrade': typeof AppUpgradeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/booking'
    | '/login'
    | '/onboarding'
    | '/app/analytics'
    | '/app/appointments'
    | '/app/calendar'
    | '/app/clients'
    | '/app/settings'
    | '/app/today'
    | '/app/upgrade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/booking'
    | '/login'
    | '/onboarding'
    | '/app/analytics'
    | '/app/appointments'
    | '/app/calendar'
    | '/app/clients'
    | '/app/settings'
    | '/app/today'
    | '/app/upgrade'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/booking'
    | '/login'
    | '/onboarding'
    | '/app/analytics'
    | '/app/appointments'
    | '/app/calendar'
    | '/app/clients'
    | '/app/settings'
    | '/app/today'
    | '/app/upgrade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BookingRoute: typeof BookingRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/upgrade': {
      id: '/app/upgrade'
      path: '/upgrade'
      fullPath: '/app/upgrade'
      preLoaderRoute: typeof AppUpgradeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/today': {
      id: '/app/today'
      path: '/today'
      fullPath: '/app/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appointments': {
      id: '/app/appointments'
      path: '/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppClientsRoute: typeof AppClientsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTodayRoute: typeof AppTodayRoute
  AppUpgradeRoute: typeof AppUpgradeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppClientsRoute: AppClientsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTodayRoute: AppTodayRoute,
  AppUpgradeRoute: AppUpgradeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BookingRoute: BookingRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
